#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page

sudo apt update
sudo apt install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
echo "server {
	listen 80 default_server;
	listen[::]:80 default_server;

	root /var/www/html;
	index index.html;

	location /redirect_me {
		return 301 http://www.makau.tech;
	}

	error_page 404 /404.html;
	location = /404.html {
	internal;
	}
}" | sudo tee /etc/nginx/sites-available/default/default
sudo service nginx restart
