#!/usr/bin/env bash
# add a custom Nginx response header

sudo apt update
sudo apt install -y nginx

sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www

echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	add_header X-Served-By $HOSTNAME;
	root /var/www/html;
	index index.html;
	location /redirect_me {
		return 301 http://makau.tech;
	}
	error_page 404 /404.html;
	location = /404.html{
		internal;
	}
}" > default
sudo mv -f default /etc/nginx/sites-available/default
sudo nginx -t
sudo service nginx restart
