#!/usr/bin/env bash
# find out what is keeping Ubuntu Nginx installation from listening on port 80
cat /etc/nginx/sites-available/default > /etc/nginx/sites-enabled/default
sudo service nginx enable
sudo service nginx restart
