#!/usr/bin/env bash
# Create the PID file

echo $$ >> /var/run/myscript.pid

# Trap signals
trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'exit' SIGQUIT
# Main loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
