#!/usr/bin/env bash
# Print text 10 times replace some of the text
j=1
while [ $j -le 10 ]; do
	if [ $j -eq 4 ]; then
		echo "bad luck"
	elif [ $j -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((j++))
done
