#!/usr/bin/env bash

j=1
while [ $j -le 20 ]; do
	case $j in
		4)
			echo "$j"
			echo "bad luck from China"
			;;

		9)
			echo "$j"
			echo "bad luck from Japan"
			;;

		17)
			echo "$j"
			echo "bad luck from Italy"

			;;
		*)
			echo "$j"
			;;
	esac
	((j++))
done
