#!/usr/bin/env bash
# Read file and print its status: exists, is empty or not and is regular 
if [ -e "school" ]; then
	echo "School file exists"

	if [ ! -s "school" ]; then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi

	if [ -f "school" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
