#!/usr/bin/env bash

# Script to configure Ubuntu server.
# 1. resolve local host to 127.0.0.2 (default is 127.0.0.1)
# 2. resolve facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.new

# create a backup of /etc/hosts
cp /etc/hosts /etc/hosts.bak

# resolve to new ip addresses in new hosts file
echo "127.0.0.2 localhost" > ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new

cp -f ~hosts.new /etc/hosts
