#!/usr/bin/env bash
# This script displays all active IPv4 addresses on the machine.

if command -v ip &> /dev/null; then
    # Using 'ip' to get IPv4 addresses
    ip -4 addr show | grep -oP '(?<=inet\s)\d+\.\d+\.\d+\.\d+'
else
    # Fallback to 'ifconfig' if 'ip' is not available
    ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -d ' ' -f2
fi
