#!/usr/bin/env bash
# Fix webserver to run nginx as user listening on port 8080

sed -i 's/user  nginx;/user  www-data;/g' /etc/nginx/nginx.conf
sed -i 's/80;/8080;/g' /etc/nginx/sites-available/default

chmod 644 /etc/nginx/nginx.conf
pkill apache2

sudo -u service nginx restart
