#!/usr/bin/env bash
# improve on run nginx as nginx user
sed -i 's/user  nginx;/user  www-data;/' /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u service nginx start
